### ISSUE TITLE
Bad Configuration for docker 

### ISSUE THREAD

**Issue by bozoweed** [cjmanca/plex-credits-detect#29]
hello i get this message : A library section has invalid information: /data/movies

but i give all volumes access .... 
/plex=/data
/plex2=/data2
/plex3=/data3
/plex4=/data4

can you made a better exemple of use for full docker environement ? 

this is my config for docker-compose.yml
```
plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
      - ${ROOT2}/complete:/data2 # media library
      - ${ROOT3}/complete:/data3 # media library
      - ${ROOT4}/complete:/data4 # media library

  plex-credits-detect:
    container_name: plex-credits-detect
    image: cjmanca/plex-credits-detect:main
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/config/plex-credits-detect:/config # plex-credits-detect database
      - ${ROOT}/config/plex/db/Library/Application Support/Plex Media Server/Plug-in Support/Databases/:/PlexDB # plex database
      - ${ROOT}/complete:/plex # media library
      - ${ROOT2}/complete:/plex2 # media library
      - ${ROOT3}/complete:/plex3 # media library
      - ${ROOT4}/complete:/plex4 # media library
```
